# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "conferences", :force => true do |t|
    t.column "name", :string, :limit => 100, :default => "", :null => false
  end

  create_table "elections", :force => true do |t|
    t.column "event_id",   :integer,                :null => false
    t.column "name",       :string
    t.column "type",       :string,   :limit => 50
    t.column "conditions", :text
    t.column "start_time", :datetime
    t.column "end_time",   :datetime
  end

  add_index "elections", ["event_id"], :name => "election_event_idx"
  add_index "elections", ["start_time", "end_time"], :name => "election_times_idx"

  create_table "events", :force => true do |t|
    t.column "name",          :string,   :limit => 100, :default => "",    :null => false
    t.column "conference_id", :integer,                                    :null => false
    t.column "location",      :string
    t.column "start_time",    :datetime
    t.column "end_time",      :datetime
    t.column "description",   :text
    t.column "active",        :boolean,  :limit => nil, :default => false, :null => false
  end

  add_index "events", ["conference_id"], :name => "event_conf_idx"
  add_index "events", ["start_time", "end_time"], :name => "event_time_idx"
  add_index "events", ["active"], :name => "event_active_idx"

  create_table "items", :force => true do |t|
    t.column "name",        :string,                  :default => "",   :null => false
    t.column "event_id",    :integer,                                   :null => false
    t.column "description", :text
    t.column "type",        :string,   :limit => 50,  :default => "",   :null => false
    t.column "start_time",  :datetime
    t.column "end_time",    :datetime
    t.column "location",    :string
    t.column "active",      :boolean,  :limit => nil, :default => true, :null => false
  end

  add_index "items", ["start_time", "end_time"], :name => "item_time_idx"
  add_index "items", ["event_id"], :name => "item_event_idx"
  add_index "items", ["type"], :name => "item_type_idx"
  add_index "items", ["active"], :name => "item_active_idx"

  create_table "participants", :force => true do |t|
    t.column "person_id", :integer,               :null => false
    t.column "item_id",   :integer,               :null => false
    t.column "role",      :string,  :limit => 25
  end

  add_index "participants", ["person_id", "item_id", "role"], :name => "participant_role_idx"

  create_table "people", :force => true do |t|
    t.column "username",     :string, :limit => 50
    t.column "first_name",   :string, :limit => 100
    t.column "middle_name",  :string, :limit => 100
    t.column "last_name",    :string, :limit => 100
    t.column "email",        :string
    t.column "organization", :string
    t.column "title",        :string
  end

  add_index "people", ["username", "email"], :name => "people_user_idx"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "votes", :force => true do |t|
    t.column "election_id", :integer,                 :null => false
    t.column "person_id",   :integer,                 :null => false
    t.column "item_id",     :integer,                 :null => false
    t.column "score",       :integer,  :default => 1, :null => false
    t.column "created_at",  :datetime,                :null => false
  end

  add_index "votes", ["election_id", "person_id", "item_id"], :name => "vote_ballot_idx"

end
